### ISSUE TITLE
Add PY3 builds

### ISSUE THREAD

**Issue by rth** [conda-forge/pyabel-feedstock#1]
First issue in this new pyabel feedstock repo! Thanks so much to all the conda-forge team for making this possible !

For now this conda-forge setup appears to create only a python2.7 build (built against numpy111),

 ```bash
conda search pyabel                             
Fetching package metadata .........
pyabel                    .  0.7.6               np111py27_0  conda-forge 
````
We would need to add builds for at least PY3.4 PY3.5 (PY3.6 would be great too) and several numpy versions. Not sure how this works (need to read some docs), I imagine conda-forge  has some preconfigured numpy-version /  Python-version build matrix...  cc. @DanHickstein @stggh

**Comment by ocefpaf** [comment]
The absence of Python 3.5 and 3.6 is odd and I will investigate, but `conda-forge` dropped support for Python 3.4 and NumPy 1.10.x recently so those version won't be available.

**Comment by ocefpaf** [comment]
I see some failures in the CIs due to the introduction of NumPy 1.12 before the binaries were up. `OS X` and Windows are fine due to splited the matrix build. Only Linux needs a restart to pick up that numpy version and complete the CI.

**Comment by ocefpaf** [comment]
Actually, the issue is the lack of SciPy for NumPy 1.12! We can either skip NumPy 1.12 for now or wait for that SciPy yo become available.

**Comment by rth** [comment]
@ocefpaf Thanks for investigating this. I think that numpy 1.12 is not critical for now, we could just disable temporarly..

**Comment by ocefpaf** [comment]
OK. Working on that now.

**Comment by rth** [comment]
@ocefpaf So how does one know which numpy versions conda-forge supports building against? Is it documented somewhere (I couldn't find anything)? 
For instance, `conda search scikit-learn | grep  conda-forge ` still yields some builds with `np110`  and the numpy-1.10.x package is still around. Does it mean that if one set `CONDA_NPY=110` the build would fail? 

Sorry about all the questions )

**Comment by ocefpaf** [comment]
> @ocefpaf So how does one know which numpy versions conda-forge supports building against? Is it documented somewhere (I couldn't find anything)? 

We do not have docs on that yet. But one can look at how the CIs are configured in [conda-smithy](https://github.com/conda-forge/conda-smithy/blob/50e02ef4e104c2d726f9992727bcb1c9e828b6a9/conda_smithy/configure_feedstock.py#L566).

> For instance, `conda search scikit-learn | grep  conda-forge ` still yields some builds with `np110`  and the numpy-1.10.x package is still around.

Those are old builds. We do not remove them.

> Does it mean that if one set `CONDA_NPY=110` the build would fail? Or it is just general agreement to drop 1.10.x?

General agreement. That is mostly due to our CI resource limitation. We added `Python 3.6`, then we had to drop `Python 3.4`. We added `numpy 1.12`, we had to drop `numpy 1.10`.

> Sorry for all the questions )

No problem. Hope that clarifies it.

**Comment by rth** [comment]
Yep, thanks a lot for these explanations!

**Comment by DanHickstein** [comment]
Thanks @rth and @ocefpaf!

**Comment by ocefpaf** [comment]
BTW scipy+numpy 1.12 should be available later today. Feel free to remove that skip and r0-erender tomorrow to close #3
